version: '3.8'

services:
  # Configuración del servicio mysql
  mysqldb:
    image: mysql # Imagen a utilizar
    # Ubicación de las variables de entorno a utilizar
    env_file: ./.env 
    # Variables de entorno definidas por el archivo .env 
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    # Puerto de la base de datos
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  # Configuración del servicio de la app de Node.js
  app:
    # Ubicación del Dockerfile para crear el servicio de Node.js
    build: .
    # Servicio del que depende
    depends_on:
      - mysqldb
    # Comunicación entre los dos servicios
    links:
      - mysqldb
    # Puertos del aplicación
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
